/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CustomTimeCard: typeof import('./src/components/overlayCards/CustomTimeCard.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconLayoutBill: typeof import('~icons/layout/bill')['default']
    IconLayoutChart: typeof import('~icons/layout/chart')['default']
    IconLayoutEdit: typeof import('~icons/layout/edit')['default']
    IconLayoutLeft: typeof import('~icons/layout/left')['default']
    IconLayoutMenu: typeof import('~icons/layout/menu')['default']
    IconLayoutUser: typeof import('~icons/layout/user')['default']
    IconSvgCalendar: typeof import('~icons/svg/calendar')['default']
    IconSvgChart: typeof import('~icons/svg/chart')['default']
    IconSvgClock: typeof import('~icons/svg/clock')['default']
    IconSvgCloud: typeof import('~icons/svg/cloud')['default']
    IconSvgMangosteen: typeof import('~icons/svg/mangosteen')['default']
    IconSvgPig: typeof import('~icons/svg/pig')['default']
    LineChart: typeof import('./src/components/charts/LineChart.vue')['default']
    NumberPad: typeof import('./src/components/inputPad/NumberPad.vue')['default']
    PieChart: typeof import('./src/components/charts/PieChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanNumberKeyboard: typeof import('vant/es')['NumberKeyboard']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanPopup: typeof import('vant/es')['Popup']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
